version: "3"

services:
  mongo:
    image: "mongo:4.4.4"
    ports:
      - "27017:27017"
  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
