FROM rust:1.50 as builder
WORKDIR /usr/src/fs-store
COPY . .
RUN cargo install --path .

FROM debian:buster-slim
RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/fs-store /usr/local/bin/fs-store

ENTRYPOINT [ "/bin/bash" ]
